services:

    netvlies.form.field:
        class: Netvlies\Bundle\FormBundle\Admin\FieldAdmin
        arguments:
          - null
          - Netvlies\Bundle\FormBundle\Entity\Field
          - NetvliesFormBundle:FieldAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: Forms, label: Fields }

    netvlies.form.field_type:
        class: Netvlies\Bundle\FormBundle\Admin\FieldTypeAdmin
        arguments:
          - null
          - Netvlies\Bundle\FormBundle\Entity\FieldType
          - NetvliesFormBundle:FieldTypeAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: Forms, label: Field types, show_in_dashboard: false }

    netvlies.form.form:
        class: Netvlies\Bundle\FormBundle\Admin\FormAdmin
        arguments:
          - null
          - Netvlies\Bundle\FormBundle\Entity\Form
          - NetvliesFormBundle:FormAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: Forms, label: Forms }

    netvlies.form:
        class: Netvlies\Bundle\FormBundle\Service\FormService
        calls:
          - [ setContainer, [@service_container] ]

    netvlies.form.twig.extension:
        class: Netvlies\Bundle\FormBundle\Twig\Extension\FormExtension
        calls:
          - [ setContainer, [@service_container] ]
        tags:
          - { name: twig.extension }
